language: java
jdk:
- openjdk8
addons:
  apt:
    packages:
    - libc6:i386 # these two packages are needed by the launch4j maven plugin to work
    - libstdc++6:i386
before_install:
- mvn clean # this actually installs a dependency
before_deploy:
- mvn package -DskipTests=true -f travis-ci/wrapper-for-mac/pom.xml
- mvn package -DskipTests=true -f travis-ci/wrapper-for-windows/pom.xml
- bash travis-ci/scripts/zip-and-move-wrapper-for-mac.sh
- export filename=$(bash travis-ci/scripts/get-amidst-filename.sh)
